[package]
name = "dj8"
version = "0.1.0"
authors = ["fuyutarow <fuyutarow@gmail.com>"]
edition = "2018"

[lib]
name = "cli"
path = "src/lib/mod.rs"

[dependencies]
ghakuf = "0.5.6"
serde_json = "1.0.64"
structopt = "0.3.21"
