[tasks.play-soviet]
script = '''
abc2midi data/soviet.abc -o data/soviet.mid && timidity $_
'''

[tasks.fix]
script = '''
# cargo fix
cargo clippy
cargo test
'''

[tasks.play-sine]
script = '''
cargo run --example synthrs
afplay out/sine.wav
'''
